### ISSUE TITLE
Make a tagged release

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/treniformis#20]
Need to add files

- [x] VERSION
- [x] Changes.md
- [x] edit setup.py to read the version number from `VERSION` like https://github.com/SkyTruth/benthos-pipeline/blob/master/setup.py

Then put the release version number in VERSION and document changes since the previous version in changes.md.

To create a new release  

- Make an issue like https://github.com/SkyTruth/benthos-pipeline/issues/728
- make a new branch
- update VERSION and changes.md
- push the branch and make a PR like https://github.com/SkyTruth/benthos-pipeline/pull/755
- merge the PR and then create a new release https://github.com/GlobalFishingWatch/treniformis/releases

**Comment by bitsofbits** [comment]
@pwoods25443,  I'm putting this together

* What should I use for the initial version? `0.1` is what's currently in `setup.py`.  `0.2`? `1.0`?

* Is it OK if I use `CHANGES.md` rather than `Changes.md`? The former matches `benthos-pipeline` and the other README-ish files as well.

**Comment by pwoods25443** [comment]
@bitsofbits let's use 0.1 for the version, and yes - CHANGES.md is fine

Let's modify it so that setup.py reads from the VERSION file like in benthos-pipeline.  I prefer not to edit setup.py just for a version change.

**Comment by pwoods25443** [comment]
@bitsofbits can we close this?
