### ISSUE TITLE
Parameterize table name 

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/treniformis#21]
We should consider parameterizing the table names in all of the sql queries and getting the table name from a master config file

**Comment by bitsofbits** [comment]
I was thinking of switching the SQL queries to using Python style `format`ing, so we could use `query = sql.format(**dict_of_values)` to pass the date in. This would also make it easy to pass in table names and whatever else we like.

Should that config file be json, or something else?
