### ISSUE TITLE
Version not available from python interface

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/treniformis#25]
Version is (or will be soon) storedin VERSION file. Can we inject this into the 
`__init__.py` so that version is accessible.
- Copy version into source on install.
- read VERSION into version.

**Comment by pwoods25443** [comment]
benthos-pipeline does this in __init.py__ like this

```python
import pkg_resources
__version__ = pkg_resources.get_distribution('benthos-pipeline').version
```

see https://github.com/SkyTruth/benthos-pipeline/blob/master/benthosp/__init__.py#L9
