### ISSUE TITLE
Use new bigquery tables

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/treniformis#28]
-  [x] DEPENDS ON https://github.com/SkyTruth/benthos-pipeline/issues/800

Use the new "740" series of pipeline output tables in bigquery.

These are

```
world-fishing-827:pipeline_740__normalize
world-fishing-827:pipeline_740__measures
world-fishing-827:pipeline_740__classify
world-fishing-827:pipeline_740__tileset
```

**Comment by bitsofbits** [comment]
Should implement #21 first / at the same time to make this easy

**Comment by pwoods25443** [comment]
@bitsofbits the bigquery tables needed for this are now ready
