### ISSUE TITLE
Look at Known Fishing Queries

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/treniformis#59]
They look suspicious to me since both the 2014 and 2015 query are looking at the same lists. In any event, I'd like to parameterize them so that they use a single query if possible.

**Comment by davidkroodsma** [comment]
@bitsofbits I just took a look at this, and they are exactly the same except for 2015 queries:

``` SELECT
    mmsi,
    shipname,
    callsign,
    '' AS imo,
    national_id,
    'ITU' AS source
  FROM
    [Registry_matching_sources.ITU_Dec_2015_Fishing]```

I think you should scrap 2014 and just use the 2015 query for everything? Or is there a reason to exclude these ITU vessels from before 2015?

@Bjorn-skytruth is there a reason not to include known vessels form the ITU 2015 matched lists for 2012 to 2014?

also, we are going to have to add the 2016 ITU list.

**Comment by bitsofbits** [comment]
@Bjorn-skytruth, I think @davidkroodsma  was trying to ping you above, but it accidentally got quoted. Care to weight in?

**Comment by Bjorn-skytruth** [comment]
@bitsofbits @davidkroodsma It would be better to apply a date range to each ITU record but this may not be practical. We now have further lists from September and December that we should extract data from. We do have cases of mmsi's being reassigned to completely different vessels so I am reluctant to just apply all records to all years.

**Comment by davidkroodsma** [comment]
@Bjorn-skytruth if we were to be adding time ranges to the ITU list, how would we do that?

**Comment by Bjorn-skytruth** [comment]
@davidkroodsma The date range would be from when the list was issued with a particular mmsi - vessel identity until the date of issue for a subsequent list which gives a different identity for that mmsi.

**Comment by davidkroodsma** [comment]
Okay -- I'm going to close this for now, as we're going to use the new lists that @bitsofbits and I and @juanmayorgahenao just developed. But we should put on the roadmap having time ranges. around these lists.
