### ISSUE TITLE
Version Data

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/treniformis#7]
We currently reference files on GCS, but we should be pulling from some versioned location, ideally this git repo and its version tags. This lets us be more confident about what data was used where, as highlighted in SkyTruth/benthos-pipeline#474.

There are of course some continuity issues with deploying from GitHub, so maybe we should set up some hooks to mirror the repo in Google's source control service.

(From https://github.com/GlobalFishingWatch/vessel-lists/issues/11)

**Comment by geowurster** [comment]
@bitsofbits I think just using tagged releases and pushing to PyPI will work.
